# Generated by Django 5.2.6 on 2025-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
