# Generated by Django 5.2.6 on 2025-09-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discountcode_usage_limit_discountcode_used_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-expires_at'], 'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
    ]
