# Generated by Django 5.2.6 on 2025-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_contact', '0002_contactus_read_contactus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
