# Generated by Django 5.2.6 on 2025-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_date',
            field=models.DateTimeField(null=True),
        ),
    ]
