# Generated by Django 5.2.6 on 2025-09-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_order', '0002_alter_order_pay_date'),
        ('poushia_products', '0006_color_size_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poushia_products.color', verbose_name='رنگ انتخابی'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poushia_products.size', verbose_name='سایز انتخابی'),
        ),
    ]
