# Generated by Django 5.2.6 on 2025-09-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_order', '0003_orderdetail_selected_color_orderdetail_selected_size'),
        ('poushia_products', '0008_product_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poushia_order.order', verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poushia_products.product', verbose_name='نام محصول'),
        ),
    ]
