# Generated by Django 5.2.6 on 2025-09-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
