# Generated by Django 5.2.6 on 2025-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_products', '0002_alter_product_options_product_brand_product_rating_and_more'),
        ('poushia_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='poushia_products_category.productcategory', verbose_name='دسته بندی'),
        ),
    ]
