# Generated by Django 5.2.6 on 2025-09-16 09:30

import django.db.models.deletion
import poushia_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_products', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=poushia_products.models.upload_image_gallery, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poushia_products.product')),
            ],
        ),
    ]
