# Generated by Django 5.2.6 on 2025-09-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_products', '0006_color_size_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایز'},
        ),
    ]
