# Generated by Django 5.2.6 on 2025-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_products', '0007_alter_color_options_alter_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='تعداد مشاهده'),
        ),
    ]
