# Generated by Django 5.2.6 on 2025-09-16 20:42

import poushia_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=200, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(max_length=200, verbose_name='شماره تماس')),
                ('fax', models.CharField(max_length=200, verbose_name='فکس')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('copyright', models.CharField(max_length=250, verbose_name='کپی رایت')),
                ('about', models.TextField(verbose_name='درباره ما')),
                ('instagram', models.URLField(verbose_name='ادرس اینستاگرام')),
                ('telegram', models.URLField(verbose_name='ادرس تلگرام')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=poushia_settings.models.upload_image, verbose_name='تصویر')),
            ],
        ),
    ]
