# Generated by Django 5.2.6 on 2025-09-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poushia_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
